theme: jekyll-theme-architect
title: "Welcome to the site of The Interactions Between Agricultural Expansion and Conservation Prioritization, Discourse, and Practice: a Multi-Scalar Analysis in the Amazon Basin"
description: "Project sponsored by SESYNC "
