theme: jekyll-theme-architect
title: "Ag-frontiers. A project sponsored by SESYNC"
description: "Welcome to the site of The Interactions Between Agricultural Expansion and Conservation Prioritization, Discourse, and Practice: a Multi-Scalar Analysis in the Amazon Basin"
